### ISSUE TITLE
Set up backend auth

### ISSUE THREAD

**Issue by alyoung1991** [FarzamA/BeatMatch#1]
Setup back end user authentication:

- Add User model
- Add routing for `api/users`
> `/registration`
> `/login`
> `/current`
- Add Validations
- Add web token authentication (jwt)

**Comment by elliot-wilson** [comment]
@alyoung1991 @FarzamA @jhkl12 are we going to allow users to upload a profile photo?

right now, the user profile details box will either look for `user.photoUrl` and display that or use a [FontAwesome headphone icon](https://fontawesome.com/v5.15/icons/headphones-alt?style=solid) if undefined.
