### ISSUE TITLE
Build Song Playlist Generation

### ISSUE THREAD

**Issue by alyoung1991** [FarzamA/BeatMatch#10]
Build song playlist generation functionality. High-level overview of playlist generation functionality is as follows:
1. Form responses are translated into floating point values corresponding to song traits (Danceability, Loudness, etc.)
2. Kaggle will receive responses and return a list of song's matching the user's response values.
3. Playlist will be presented to the frontend with ability to export to Spotify

**Comment by zkural1** [comment]
Finished
