### ISSUE TITLE
Build User Profile Frontend

### ISSUE THREAD

**Issue by alyoung1991** [FarzamA/BeatMatch#5]
![Screen Shot 2021-11-15 at 11 09 49 AM](https://user-images.githubusercontent.com/87868033/141838860-014c9ef2-51a5-4e66-bc5c-389e001c6c7a.png)

**Comment by elliot-wilson** [comment]
Basic layout is complete.

Still to do:

(1) Once playlists are built, find way of displaying them artfully (perhaps with thumbnails of first 4 songs as preview image).

(2) Is there more data that can be displayed in the profile details box on the right?
